# Generated by Django 6.0.3 on 2026-05-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=120)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('vet_name', models.CharField(max_length=120)),
                ('reminder_days_before', models.PositiveIntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='api.vaccination')),
            ],
        ),
    ]
